export LD_LIBRARY_PATH=/projects/ucsd/software/deps/lib:/projects/ucsd/software/CalVR/lib:/opt/OpenSceneGraph-2.9.7/lib64:/opt/tiff-4.0.0beta7/lib64:/opt/Coin-3.1.3/lib64:/opt/simage-1.7.0/lib64:/projects/software/calvr_sl6/deps/lib:${LD_LIBRARY_PATH}
export PATH=/projects/ucsd/software/CalVR/bin:${PATH}

##export OSG_HOME=/home/covise/covise/extern_libs
##export MXML_HOME=/projects/ucsd/deps

export CALVR_HOME=/projects/ucsd/software/CalVR

